[env]
BUILDKIT_HOST = "docker-container://buildkit"

[tasks.setup]
run = [
  "mise install",
  "docker run --rm --privileged -d --name buildkit moby/buildkit || true",
  "mise run tidy",
]

[tasks.cli]
run = "go run cmd/cli/main.go"

[tasks.build]
run = "go build -o bin/railpack cmd/cli/main.go"

[tasks.clean]
run = "rm -rf bin dist docs/dist"

[tasks.test]
run = "go test -short ./..."

[tasks.test-integration]
run = "go test -v ./integration_tests"

[tasks.test-update-snapshots]
run = "UPDATE_SNAPS=true go test -short ./..."

[tasks.check]
run = """
go vet ./...
go fmt ./...
golangci-lint run
"""

[tasks.tidy]
run = "go mod tidy"

[tasks.docs-build]
dir = "docs"
run = "bun run build"

[tasks.docs-dev]
dir = "docs"
run = "bun run dev"

[tools]
go = "1.23.4"
golangci-lint = "1.63.4"
bun = "1.2"
node = "22"
"go:github.com/wagoodman/dive" = "latest"

[settings]
experimental = true
